# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f6e88f8a656c6a3f3ca877e5d95c126a00714d661e7a696b8dd66b2d0f946b5bed5c0cb00c3c2cb7880e17e22861e2b93141af8718b5b4d951652b975d70d5

test:
  secret_key_base: f764cf6e0b5d317925aa63fb23e4fc7e2f2b2451902d2f3fb746106a3ee490f93d5fdbb68cfba3e6089b5306f9a30314a0fb1a4437d8127e4ddf1d7e934094e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
